[package]
name = "sail-telemetry"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
sail-common = { path = "../sail-common" }

thiserror = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
env_logger = { workspace = true }
fastrace = { workspace = true }
fastrace-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
