[package]
name = "sail-logical-plan"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
sail-common = { path = "../sail-common" }
sail-common-datafusion = { path = "../sail-common-datafusion" }

datafusion = { workspace = true }
datafusion-common = { workspace = true }
datafusion-expr = { workspace = true }
comfy-table = { workspace = true }
html-escape = { workspace = true }
log = { workspace = true }
educe = { workspace = true }
