[package]
name = "framework-python"
version = "0.1.0"
edition = "2021"

[dependencies]
framework-proto = { path = "../framework-proto" }
datafusion = { workspace = true }
datafusion-expr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pyo3 = { workspace = true }
