[package]
name = "sail-server"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
sail-common = { path = "../sail-common" }
sail-telemetry = { path = "../sail-telemetry" }

tokio = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tonic-health = { workspace = true }
fastrace = { workspace = true }
tower = { workspace = true }
log = { workspace = true }
axum = { workspace = true }
