[package]
name = "sail-session"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
sail-common = { path = "../sail-common" }
sail-common-datafusion = { path = "../sail-common-datafusion" }
sail-catalog = { path = "../sail-catalog" }
sail-catalog-memory = { path = "../sail-catalog-memory" }
sail-catalog-iceberg = { path = "../sail-catalog-iceberg" }
sail-catalog-unity = { path = "../sail-catalog-unity" }
sail-data-source = { path = "../sail-data-source" }
sail-delta-lake = { path = "../sail-delta-lake" }
sail-iceberg = { path = "../sail-iceberg" }
sail-logical-optimizer = { path = "../sail-logical-optimizer" }
sail-plan-lakehouse = { path = "../sail-plan-lakehouse" }

datafusion = { workspace = true }
secrecy = { workspace = true }
