[package]
name = "sail-session"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
sail-common = { path = "../sail-common" }
sail-catalog = { path = "../sail-catalog" }
sail-catalog-memory = { path = "../sail-catalog-memory" }
sail-catalog-iceberg = { path = "../sail-catalog-iceberg" }
sail-catalog-unity = { path = "../sail-catalog-unity" }

datafusion = { workspace = true }
secrecy = { workspace = true }