[package]
name = "sail-python"
version = { workspace = true }
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
sail-common = { path = "../sail-common" }
sail-telemetry = { path = "../sail-telemetry" }
sail-spark-connect = { path = "../sail-spark-connect" }
sail-cli = { path = "../sail-cli" }

pyo3 = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
fastrace = { workspace = true }

[lib]
crate-type = ["cdylib"]
