name: Gold data report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/commit-baseline
        id: baseline

      - uses: actions/checkout@v4
        with:
          path: tmp/baseline
          ref: ${{ steps.baseline.outputs.sha }}

      - name: Generate gold data report
        env:
          REPORT_GIT_REF_BEFORE: ${{ steps.baseline.outputs.ref }}
          REPORT_GIT_REF_AFTER: ${{ github.ref }}
        run: |
          scripts/common-gold-data/report.sh . tmp/baseline > tmp/report.md
          cat tmp/report.md >> "$GITHUB_STEP_SUMMARY"

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: gold-data-report
          path: tmp/report.md
          retention-days: 1

  report:
    name: Report
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs:
      - run
    steps:
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: gold-data-report
          path: tmp

      - name: Publish report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gold-data-report
          path: tmp/report.md
