name: Report

on:
  # When this workflow is triggered, the workflow definition comes from the `main` branch.
  # If a pull request modifies this file, it will have an effect only after the pull request is merged.
  workflow_run:
    workflows: ["Build", "Gold Data"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  report:
    name: Report
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      # The Spark tests are not always run,
      # so we ignore the error if the artifact is not found.

      - uses: ./.github/actions/pull-request-report
        if: github.event.workflow_run.name == 'Build'
        continue-on-error: true
        with:
          workflow_run_id: ${{ github.event.workflow_run.id }}
          artifact_name: spark-3.5.7-test-report
          report_name: spark-3.5.7-test

      - uses: ./.github/actions/pull-request-report
        if: github.event.workflow_run.name == 'Build'
        continue-on-error: true
        with:
          workflow_run_id: ${{ github.event.workflow_run.id }}
          artifact_name: spark-4.1.1-test-report
          report_name: spark-4.1.1-test

      - uses: ./.github/actions/pull-request-report
        if: github.event.workflow_run.name == 'Build'
        continue-on-error: true
        with:
          workflow_run_id: ${{ github.event.workflow_run.id }}
          artifact_name: ibis-test-report
          report_name: ibis-test

      - uses: ./.github/actions/pull-request-report
        if: github.event.workflow_run.name == 'Gold Data' && github.event.workflow_run.conclusion == 'success'
        with:
          workflow_run_id: ${{ github.event.workflow_run.id }}
          artifact_name: gold-data-report
          report_name: gold-data
